lib/morphic_pro_web/router.ex
defmodule MorphicProWeb.Router do
  use MorphicProWeb, :router

  import Phoenix.LiveDashboard.Router
  import MorphicProWeb.UserAuth

  use Sentry.PlugCapture

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MorphicProWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admins_only do
    plug MorphicProWeb.Plugs.AdminsOnly
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_user
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user, :require_authenticated_user, :admins_only]
    live_dashboard "/dashboard", metrics: MorphicProWeb.Telemetry, ecto_repos: [MorphicPro.Repo]
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user, :require_authenticated_user]
    delete "/users/logout", UserSessionController, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user]
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/", MorphicProWeb do
    pipe_through :browser

    live "/posts/:slug/edit", PostLive.Action, :edit
    live "/snaps/:slug/edit", SnapLive.Action, :edit

    live "/posts/new", PostLive.Action, :new
    live "/snaps/new", SnapLive.Action, :new

    live "/posts/tags/:tag", PostLive.Index, :tag
    live "/snaps/tags/:tag", SnapLive.Index, :tag

    live "/posts/:slug", PostLive.Show, :show
    live "/snaps/:slug", SnapLive.Show, :show

    live "/posts", PostLive.Index, :index
    live "/snaps", SnapLive.Index, :index

    live "/about", PageLive.About, :about
    live "/privacy", PageLive.Privacy, :privacy

    live "/terms", PageLive.Terms, :terms

    live "/", PageLive.Index, :index
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Other scopes may use custom stacks.
  scope "/api", MorphicProWeb do
    pipe_through [:api, :admins_only]

    put "/gen_presigned_url", PresignedUrlController, :gen_presigned_url
  end
end

lib/morphic_pro_web/views/layout_view.ex
defmodule MorphicProWeb.LayoutView do
  # FYI: If you add any logic besure to unignore from coveralls.json
  use MorphicProWeb, :view
end

lib/morphic_pro_web/templates/layout/_footer.html.eex
<footer class="w-full pb-6 bg-gray-900">
  <div class="py-20 bg-gray-800">
    <div class="text-center">

      <h4 class="text-3xl font-bold text-gray-100 content-primed">
        <span class="pr-1 font-extralight text-white display-block icon-shape logo"></span> Morphic Pro
      </h4>

      <div class="mt-3 text-white">
        (971) 533-7446 | <a href="mailto:hello@morphic.pro">hello@morphic.pro</a>
      </div>
      <div class="mt-2 text-white">
        Portland, Oregon <i class="text-green-400 fas fa-tree"></i>
      </div>


      <div class="mt-5 text-2xl text-white">
        <span class="mr-2">
          <a href="https://github.com/MorphicPro" class="hover:text-blue-700"><i class="fab fa-github"></i></a>
        </span>
      </div>
    </div>
  </div>

  <div class="pt-10 text-sm text-gray-400 bg-gray-900">
    <div class="container flex flex-wrap items-center justify-between w-full mx-auto">
      <div class="w-full px-4 lg:w-auto lg:static lg:block lg:justify-start">
        <span><i class="far fa-copyright"></i></i> 2020 Morphic Pro, LLC - All Rights Reserved.</span>
      </div>

      <div class="items-center flex-grow w-full px-4 lg:w-auto lg:static lg:block lg:justify-start lg:flex">
        <ul class="flex flex-col list-none lg:flex-row lg:ml-auto">
          <li class="pr-4">

          </li>
          <li>
            <a href="/privacy" class="pr-4"><i class="fas fa-user-secret"></i> Privacy</a>
          </li>
          <li>
            <a href="/terms"><i class="fas fa-file-signature"></i> Terms &amp; Conditions</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

lib/morphic_pro_web/templates/layout/_header.html.eex
<nav
  class="fixed top-0 left-0 z-10 flex flex-wrap items-center justify-between w-full px-2 py-3 text-white transitions duration-700 navbar-fixed navbar-expand-lg">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <div class="relative flex justify-between w-full px-4 lg:w-auto lg:static lg:block lg:justify-start">
      <%= live_redirect to: Routes.page_index_path(@conn, :index), class: "relative inline-block py-2 ml-5 mr-4 font-bold leading-relaxed whitespace-no-wrap" do %>
      <span class="pr-1 display-block icon-shape logo"></span>
      Morphic.Pro
      <% end %>
      <button
        class="block px-3 py-1 text-xl leading-none bg-transparent border border-transparent border-solid rounded outline-none cursor-pointer lg:hidden focus:outline-none"
        type="button" onclick="window.toggleNavbar('collapse-navbar')">
        <i class="fas fa-bars"></i>
      </button>
    </div>
    <div class="items-center flex-grow hidden lg:flex" id="collapse-navbar">
      <ul class="flex flex-col list-none lg:flex-row lg:ml-auto">
        <li class="nav-item">
          <%= live_redirect to: Routes.post_index_path(@conn, :index), class: "flex items-center px-3 py-2 text-xs font-normal leading-snug uppercase transition-opacity duration-500 hover:opacity-50" do %>
          <i class="text-lg fas fa-book-open leading-lg"></i><span class="ml-2">Posts</span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= live_redirect to: Routes.snap_index_path(@conn, :index), class: "flex items-center px-3 py-2 text-xs font-normal leading-snug uppercase transition-opacity duration-500 hover:opacity-50" do %>
          <i class="text-lg fas fa-camera leading-lg"></i><span class="ml-2">Snaps</span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= live_redirect to: Routes.page_about_path(@conn, :about), class: "flex items-center px-3 py-2 text-xs font-normal leading-snug uppercase transition-opacity duration-500 hover:opacity-50" do %>
          <i class="text-lg fas fa-address-card leading-lg"></i><span class="ml-2">About</span>
          <% end %>
        </li>

        <%= if @current_user do %>
        <li class="nav-item">
          <%= link to: Routes.user_session_path(@conn, :delete), method: :delete,
          class: "flex items-center px-3 py-2 text-xs font-normal leading-snug
          uppercase transition-opacity duration-1000 hover:opacity-50" do %>
          <i class="text-lg fas fa-sign-out-alt leading-lg"></i>
          <span class="ml-2">Sign out</span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link to: Routes.user_settings_path(@conn, :edit), class: "flex
          items-center px-3 py-2 text-xs font-normal leading-snug uppercase
          transition-opacity duration-1000 hover:opacity-50" do %>
          <i class="text-lg fas fa-user-circle leading-lg"></i>
          <span class="ml-2">Account</span>
          <% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link to: Routes.user_session_path(@conn, :new), class: "flex
          items-center px-3 py-2 text-xs font-normal leading-snug uppercase
          transition-opacity duration-1000 hover:opacity-50" do %>
          <i class="text-lg fas fa-sign-in-alt leading-lg"></i><span class="ml-2">Sign In</span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link to: Routes.user_registration_path(@conn, :new), class: "flex
          items-center px-3 py-2 text-xs font-normal leading-snug uppercase
          transition-opacity duration-1000 hover:opacity-50" do %>
          <i class="text-lg fas fa-user-circle leading-lg"></i>
          <span class="ml-2">Register</span>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

lib/morphic_pro_web/templates/layout/app.html.eex
<%= @inner_content %>

lib/morphic_pro_web/templates/layout/footer.html.eex
<footer class="w-full pb-6 bg-gray-900">
  <div class="py-20 bg-gray-800">
    <div class="text-center">

      <h4 class="text-3xl font-bold text-gray-100">
        <span class="pr-1 font-thin text-white display-block icon-shape logo"></span> Morphic Pro<span class="text-xs">,
          LLC</span>
      </h4>
      <div class="mt-5 text-white text-2xl">
        <span class="mr-2">
          <a href="https://keybase.io/morphicpro" class="hover:text-orange-500"><i class="fab fa-keybase"></i></a>
        </span>
        <span class="mr-2">
          <a href="https://github.com/MorphicPro" class="hover:text-blue-700"><i class="fab fa-github"></i></a>

        </span>
        <span>
          <a rel="me" href="https://mastodon.social/@morphicpro" class="hover:text-blue-500"><i
              class="fab fa-mastodon"></i></a>
        </span>
      </div>
    </div>
  </div>

  <div class="py-10 text-sm text-gray-400 bg-gray-900">
    <div class="container flex flex-wrap items-center justify-between w-full mx-auto">
      <div class="relative flex justify-between w-full px-4 lg:w-auto lg:static lg:block lg:justify-start">
        <span><i class="fas fa-copyright"></i> 2020 Morphic Pro, LLC - All Rights Reserved.</span>
      </div>

      <div class="items-center flex-grow lg:flex">
        <ul class="flex flex-col list-none lg:flex-row lg:ml-auto">
          <li>
            <a href="/privacy" class="pr-4"><i class="fas fa-user-secret"></i> Privacy</a>
          </li>
          <li>
            <a href="/terms"><i class="fas fa-file-signature"></i> Terms &amp; Conditions</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

lib/morphic_pro_web/templates/layout/live.html.leex
<%= @inner_content %>

lib/morphic_pro_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en" class="antialiased text-gray-900">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <meta name="description" content="Portland's Digital Curator">
  <meta name="author" content="Josh Chernoff <jchernoff@morphic.pro>">

  <meta property="og:site_name" content="Morphic Pro, LLC.">
  <meta property="og:title" content="<%= assigns[:page_title] || "Morphic.Pro, LLC" %>">

  <meta property="og:image" content="<%= assigns[:page_image] || "https://morphic.pro#{Routes.static_path(@conn, "/images/logo.png")}" %>">
  <meta property="og:url" content="https://morhpic.pro<%= @conn.request_path %>">

  <meta property="og:description" content="<%= assigns[:page_description] || "Morphic.Pro, LLC" %>">

  <meta name="twitter:card" content="summary_large_image">

  <link rel="apple-touch-icon"      sizes="180x180" href="<%= Routes.static_path(@conn, "/images/apple-touch-icon.png") %>">
  <link rel="icon" type="image/png" sizes="32x32"   href="<%= Routes.static_path(@conn, "/images/favicon-32x32.png") %>">
  <link rel="icon" type="image/png" sizes="16x16"   href="<%= Routes.static_path(@conn, "/images/favicon-16x16.png") %>">

  <link rel="mask-icon" href="<%= Routes.static_path(@conn, "/images/safari-pinned-tab.svg") %>" color="#5bbad5">

  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "Morphic.Pro" %>

  <link rel="preload" href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" as="style">
  <link rel="preload" href="<%= Routes.static_path(@conn, "/fonts/icomoon.woff") %>" as="font" type="font/woff2" crossorigin>

  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/vendors~app.bundle.css") %>" />
  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.bundle.css") %>" />

  <script defer phx-track-static type="text/javascript" rel="preload" src="<%= Routes.static_path(@conn, "/js/vendors~app.bundle.js") %>"></script>
  <script defer phx-track-static type="text/javascript" rel="preload" src="<%= Routes.static_path(@conn, "/js/app.bundle.js") %>"></script>
</head>

<body class="">
  <%= render "_header.html", assigns %>
  <main class="relative h-full"><%= @inner_content %></main>
  <%= render "_footer.html", conn: @conn %>
  <%= render_existing(view_module(@conn), "script." <> view_template(@conn)) %>
</body>
</html>