lib/morphic_pro_web/router.ex
defmodule MorphicProWeb.Router do
  use MorphicProWeb, :router

  import Phoenix.LiveDashboard.Router
  import MorphicProWeb.UserAuth

  use Sentry.PlugCapture

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MorphicProWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admins_only do
    plug MorphicProWeb.Plugs.AdminsOnly
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_user
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user, :require_authenticated_user, :admins_only]
    live_dashboard "/dashboard", metrics: MorphicProWeb.Telemetry, ecto_repos: [MorphicPro.Repo]
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user, :require_authenticated_user]
    delete "/users/logout", UserSessionController, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", MorphicProWeb do
    pipe_through [:browser, :fetch_current_user]
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/", MorphicProWeb do
    pipe_through :browser

    live "/posts/:slug/edit", PostLive.Action, :edit
    live "/snaps/:slug/edit", SnapLive.Action, :edit

    live "/posts/new", PostLive.Action, :new
    live "/snaps/new", SnapLive.Action, :new

    live "/posts/tags/:tag", PostLive.Index, :tag
    live "/snaps/tags/:tag", SnapLive.Index, :tag

    live "/posts/:slug", PostLive.Show, :show
    live "/snaps/:slug", SnapLive.Show, :show

    live "/posts", PostLive.Index, :index
    live "/snaps", SnapLive.Index, :index

    live "/about", PageLive.About, :about
    live "/privacy", PageLive.Privacy, :privacy

    live "/terms", PageLive.Terms, :terms

    live "/", PageLive.Index, :index
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Other scopes may use custom stacks.
  scope "/api", MorphicProWeb do
    pipe_through [:api, :admins_only]

    put "/gen_presigned_url", PresignedUrlController, :gen_presigned_url
  end
end

lib/morphic_pro_web/controllers/user_session_controller.ex
defmodule MorphicProWeb.UserSessionController do
  use MorphicProWeb, :controller

  alias MorphicPro.Accounts
  alias MorphicProWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      if user.confirmed_at == nil do
        redirect(conn, to: Routes.user_confirmation_path(conn, :new))
      else
        UserAuth.login_user(conn, user, user_params)
      end
    else
      render(conn, "new.html", error_message: "Invalid e-mail or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.logout_user()
  end
end

lib/morphic_pro_web/views/user_session_view.ex
defmodule MorphicProWeb.UserSessionView do
  use MorphicProWeb, :view
end

lib/morphic_pro_web/templates/user_session/new.html.eex
<div class="bg-image" style="background-image: url(<%= Routes.static_path(@conn, "/images/login2.jpg") %>)">
  <div class="justify-center w-screen min-h-screen bg-black-07">
    <div
      class="h-auto pt-20 login-form md:pt-0 md:top-0 md:left-0 md:right-0 md:bottom-0 md:absolute md:my-auto md:mx-auto sm:max-w-sm">
      <h1 class="text-xl font-bold text-center text-white">Sign In</h1>
      <%= get_flash(@conn) |> Map.values |> List.to_string |> (fn string -> "<h3 class='text-center text-red-400'> #{string}</h3>" end).() |> raw %>
      <%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user, class: "px-8 pt-4 pb-2"], fn f -> %>
      <%= if @error_message do %>
      <div class="text-red-500">
        <p><%= @error_message %></p>
      </div>
      <% end %>

      <div class="">
        <%= error_tag f, :email, class: "text-red-500" %>
        <%= text_input f, :email, class: "bg-transparent shadow appearance-none border border-gray-500 w-full py-4 px-3 text-white mb-3 leading-tight focus:outline-none focus:border-white hover:border-gray-200 transition-colors duration-700", id: "username", placeholder: "Email" %>
      </div>

      <div class="">
        <%= error_tag f, :password, class: "text-red-500" %>
        <%= password_input f, :password, error_class: "border border-red-500", class: "bg-transparent shadow appearance-none border border-gray-500 w-full py-4 px-3 text-white mb-3 leading-tight focus:outline-none focus:border-white hover:border-gray-200 transition-colors duration-700", id: "password", placeholder: "Password" %>
      </div>

      <div class="">
        <%= label f, :remember_me, "Keep me logged in for 60 days" %>
        <%= checkbox f, :remember_me %>
      </div>

      <div class="">
        <%= submit "Sign In", class: "w-full border border-white text-white hover:text-gray-600 hover:bg-gray-200 font-bold py-4 px-4 focus:outline-none transition-colors duration-700" %>
      </div>
      <% end %>
      <p class="pb-2 text-center text-white">
        <%= link "Forgot Password", to: Routes.user_reset_password_path(@conn, :new) %> |
        <%= link "Register", to: Routes.user_registration_path(@conn, :new) %></p>

      <p class="text-xs text-center text-gray-500">
        &copy;2020 Morphic Pro llc. All rights reserved.
      </p>
    </div>
  </div>
</div>